local p = {
    editor_bg = "#121314",
    panel_bg = "#191A1B",
    popup_bg = "#202122",
    line_bg = "#242526",
    border = "#2A2B2C",
    border_alt = "#333536",
    fg = "#BBBEBF",
    fg_ui = "#BFBFBF",
    fg_soft = "#C9D1D9",
    fg_muted = "#8C8C8C",
    fg_dim = "#555555",
    fg_bright = "#F0F6FC",
    line_nr = "#858889",
    accent = "#3994BC",
    accent_link = "#48A0C7",
    selection = "#245C73",
    selection_soft = "#1A333D",
    search = "#1D3D4B",
    search_current = "#1E4252",
    match_paren = "#1F3E4C",
    diff_add = "#17231A",
    diff_add_text = "#274129",
    diff_delete = "#2D1919",
    diff_delete_text = "#562F2D",
    diff_change = "#5A1E02",
    diff_inserted = "#7EE787",
    diff_deleted = "#FFA198",
    diff_changed = "#FFA657",
    comment = "#8B949E",
    constant = "#79C0FF",
    variable = "#FFA657",
    variable_other = "#C9D1D9",
    func = "#D2A8FF",
    keyword = "#FF7B72",
    string = "#A5D6FF",
    tag = "#7EE787",
    type = "#4EC9B0",
    error = "#F48771",
    warning = "#E5BA7D",
    info = "#48A0C7",
    hint = "#8C8C8C",
}

return {
    color_overrides = {
        vscFront = p.fg,
        vscBack = p.editor_bg,
        vscTabCurrent = p.editor_bg,
        vscTabOther = p.panel_bg,
        vscTabOutside = p.panel_bg,
        vscLeftDark = p.panel_bg,
        vscLeftMid = p.popup_bg,
        vscLeftLight = p.line_bg,
        vscPopupFront = p.fg_ui,
        vscPopupBack = p.popup_bg,
        vscPopupHighlightBlue = "#243239",
        vscPopupHighlightGray = p.line_bg,
        vscSplitLight = p.border_alt,
        vscSplitDark = p.border,
        vscSplitThumb = p.line_nr,
        vscCursorDarkDark = p.line_bg,
        vscCursorDark = p.editor_bg,
        vscCursorLight = p.fg,
        vscSelection = p.selection,
        vscLineNumber = p.line_nr,
        vscDiffRedDark = p.diff_delete,
        vscDiffRedLight = p.diff_delete_text,
        vscDiffRedLightLight = p.diff_deleted,
        vscDiffGreenDark = p.diff_add,
        vscDiffGreenLight = p.diff_add_text,
        vscSearchCurrent = p.search_current,
        vscSearch = p.search,
        vscGitAdded = "#73C991",
        vscGitModified = p.warning,
        vscGitDeleted = p.error,
        vscGitRenamed = "#73C991",
        vscGitUntracked = "#73C991",
        vscGitIgnored = p.fg_muted,
        vscGitStageModified = p.warning,
        vscGitStageDeleted = p.error,
        vscGitConflicting = p.error,
        vscGitSubmodule = p.constant,
        vscContext = p.fg_dim,
        vscContextCurrent = p.line_nr,
        vscFoldBackground = p.popup_bg,
        vscSuggestion = "#878889",
        vscGray = p.comment,
        vscViolet = p.func,
        vscBlue = p.constant,
        vscAccentBlue = p.constant,
        vscDarkBlue = p.selection,
        vscMediumBlue = p.accent_link,
        vscDisabledBlue = p.fg_muted,
        vscLightBlue = p.string,
        vscGreen = "#73C991",
        vscBlueGreen = p.info,
        vscLightGreen = p.variable,
        vscRed = p.error,
        vscOrange = p.variable,
        vscLightRed = p.diff_deleted,
        vscYellowOrange = p.variable,
        vscYellow = p.warning,
        vscDarkYellow = "#B89500",
        vscPink = p.func,
        vscDimHighlight = p.match_paren,
    },
    group_overrides = {
        Normal = { fg = p.fg, bg = p.editor_bg },
        NormalNC = { fg = p.fg, bg = p.editor_bg },
        NormalFloat = { fg = p.fg_ui, bg = p.popup_bg },
        FloatBorder = { fg = p.border, bg = p.popup_bg },
        FloatTitle = { fg = p.fg_ui, bg = p.popup_bg, bold = true },
        Cursor = { fg = p.editor_bg, bg = p.fg },
        CursorLine = { bg = p.line_bg },
        CursorColumn = { bg = p.line_bg },
        ColorColumn = { bg = p.line_bg },
        CursorLineNr = { fg = p.fg, bg = p.editor_bg, bold = true },
        LineNr = { fg = p.line_nr, bg = p.editor_bg },
        SignColumn = { bg = p.editor_bg },
        FoldColumn = { fg = p.line_nr, bg = p.editor_bg },
        Folded = { fg = p.fg_muted, bg = p.popup_bg },
        EndOfBuffer = { fg = p.editor_bg, bg = p.editor_bg },
        WinSeparator = { fg = p.border, bg = p.editor_bg },
        VertSplit = { fg = p.border, bg = p.editor_bg },
        StatusLine = { fg = p.fg_muted, bg = p.panel_bg },
        StatusLineNC = { fg = p.fg_muted, bg = p.panel_bg },
        WinBar = { fg = p.fg_ui, bg = p.editor_bg, bold = true },
        WinBarNc = { fg = p.fg_muted, bg = p.editor_bg },
        TabLine = { fg = p.fg_muted, bg = p.panel_bg },
        TabLineFill = { fg = p.fg_muted, bg = p.panel_bg },
        TabLineSel = { fg = p.fg_ui, bg = p.editor_bg },
        Pmenu = { fg = p.fg_ui, bg = p.popup_bg },
        PmenuSel = { fg = p.fg, bg = "#243239" },
        PmenuSbar = { bg = p.line_bg },
        PmenuThumb = { bg = p.line_nr },
        Visual = { bg = p.selection },
        VisualNOS = { bg = p.selection },
        Search = { fg = p.fg_bright, bg = p.search },
        IncSearch = { fg = p.fg_bright, bg = p.search_current, bold = true },
        CurSearch = { fg = p.fg_bright, bg = p.selection, bold = true },
        MatchParen = { fg = p.fg, bg = p.match_paren, bold = true },
        Directory = { fg = p.constant },
        NonText = { fg = p.fg_dim },
        Whitespace = { fg = p.fg_dim },
        SpecialKey = { fg = p.fg_muted },
        Conceal = { fg = p.fg_muted, bg = p.editor_bg },
        Question = { fg = p.constant, bg = p.editor_bg },
        MoreMsg = { fg = p.constant, bg = p.editor_bg },
        ModeMsg = { fg = p.fg_ui, bg = p.editor_bg },
        WarningMsg = { fg = p.warning, bg = p.editor_bg },
        ErrorMsg = { fg = p.error, bg = p.editor_bg },
        DiffAdd = { fg = p.diff_inserted, bg = p.diff_add },
        DiffChange = { fg = p.diff_changed, bg = p.diff_change },
        DiffDelete = { fg = p.diff_deleted, bg = p.diff_delete },
        DiffText = { fg = p.fg_bright, bg = p.diff_add_text, bold = true },
        DiagnosticError = { fg = p.error },
        DiagnosticWarn = { fg = p.warning },
        DiagnosticInfo = { fg = p.info },
        DiagnosticHint = { fg = p.hint },
        DiagnosticOk = { fg = p.tag },
        DiagnosticSignError = { fg = p.error, bg = p.editor_bg },
        DiagnosticSignWarn = { fg = p.warning, bg = p.editor_bg },
        DiagnosticSignInfo = { fg = p.info, bg = p.editor_bg },
        DiagnosticSignHint = { fg = p.hint, bg = p.editor_bg },
        DiagnosticSignOk = { fg = p.tag, bg = p.editor_bg },
        DiagnosticVirtualTextError = { fg = p.error, bg = "#3A1D1D" },
        DiagnosticVirtualTextWarn = { fg = p.warning, bg = "#352A05" },
        DiagnosticVirtualTextInfo = { fg = p.info, bg = "#1E3A47" },
        DiagnosticVirtualTextHint = { fg = p.hint, bg = p.line_bg },
        DiagnosticVirtualTextOk = { fg = p.tag, bg = p.diff_add },
        DiagnosticFloatingError = { fg = p.error, bg = p.popup_bg },
        DiagnosticFloatingWarn = { fg = p.warning, bg = p.popup_bg },
        DiagnosticFloatingInfo = { fg = p.info, bg = p.popup_bg },
        DiagnosticFloatingHint = { fg = p.hint, bg = p.popup_bg },
        DiagnosticFloatingOk = { fg = p.tag, bg = p.popup_bg },
        DiagnosticUnderlineError = { undercurl = true, sp = p.error },
        DiagnosticUnderlineWarn = { undercurl = true, sp = p.warning },
        DiagnosticUnderlineInfo = { undercurl = true, sp = p.info },
        DiagnosticUnderlineHint = { undercurl = true, sp = p.hint },
        DiagnosticUnderlineOk = { undercurl = true, sp = p.tag },
        LspReferenceText = { bg = p.selection_soft },
        LspReferenceRead = { bg = p.selection_soft },
        LspReferenceWrite = { bg = p.selection_soft, bold = true },
        LspInlayHint = { fg = p.fg_muted, bg = p.line_bg, italic = true },
        LspCodeLens = { fg = p.fg_muted, italic = true },
        LspCodeLensSeparator = { fg = p.fg_dim },
        SpellBad = { undercurl = true, sp = p.error },
        SpellCap = { undercurl = true, sp = p.info },
        SpellRare = { undercurl = true, sp = p.func },
        SpellLocal = { undercurl = true, sp = p.warning },
        Comment = { fg = p.comment, italic = false },
        Constant = { fg = p.constant },
        String = { fg = p.string },
        Character = { fg = p.keyword },
        Number = { fg = p.constant },
        Boolean = { fg = p.constant },
        Float = { fg = p.constant },
        Identifier = { fg = p.variable },
        Function = { fg = p.func },
        Statement = { fg = p.keyword },
        Conditional = { fg = p.keyword },
        Repeat = { fg = p.keyword },
        Label = { fg = p.keyword },
        Operator = { fg = p.fg },
        Keyword = { fg = p.keyword },
        Exception = { fg = p.keyword },
        PreProc = { fg = p.keyword },
        Include = { fg = p.fg_soft },
        Define = { fg = p.keyword },
        Macro = { fg = p.keyword },
        Type = { fg = p.type },
        StorageClass = { fg = p.type },
        Structure = { fg = p.type },
        Typedef = { fg = p.type },
        Special = { fg = p.variable },
        SpecialChar = { fg = p.keyword },
        Tag = { fg = p.tag },
        Delimiter = { fg = p.comment },
        SpecialComment = { fg = p.comment },
        Underlined = { fg = p.accent_link, underline = true },
        Error = { fg = p.error, undercurl = true, sp = p.error },
        Todo = { fg = p.warning, bold = true },
        markdownBold = { fg = p.fg_soft, bold = true },
        markdownCode = { fg = p.constant },
        markdownCodeDelimiter = { fg = p.comment },
        markdownHeadingDelimiter = { fg = p.constant, bold = true },
        markdownLinkText = { fg = p.string, underline = false },
        markdownUrl = { fg = p.accent_link, underline = true },
        markdownRule = { fg = p.constant, bold = true },
        markdownQuote = { fg = p.tag },
        jsonKeyword = { fg = p.tag },
        jsonBoolean = { fg = p.constant },
        jsonNull = { fg = p.constant },
        htmlTag = { fg = p.comment },
        htmlEndTag = { fg = p.comment },
        htmlTagName = { fg = p.tag },
        htmlSpecialTagName = { fg = p.tag },
        htmlArg = { fg = p.variable_other },
        cssBraces = { fg = p.comment },
        cssTagName = { fg = p.tag },
        cssClassName = { fg = p.variable },
        cssPseudoClass = { fg = p.variable },
        cssPseudoClassId = { fg = p.variable },
        cssPseudoClassLang = { fg = p.variable },
        cssIdentifier = { fg = p.variable },
        cssProp = { fg = p.constant },
        cssDefinition = { fg = p.constant },
        cssAttr = { fg = p.string },
        cssAttrRegion = { fg = p.string },
        cssColor = { fg = p.string },
        cssFunction = { fg = p.func },
        cssFunctionName = { fg = p.func },
        cssValueNumber = { fg = p.constant },
        cssValueLength = { fg = p.constant },
        cssUnitDecorators = { fg = p.comment },
        cssImportant = { fg = p.keyword },
        ["@comment"] = { fg = p.comment, italic = false },
        ["@comment.note"] = { fg = p.constant, bold = true },
        ["@comment.warning"] = { fg = p.warning, bold = true },
        ["@comment.error"] = { fg = p.error, bold = true },
        ["@punctuation.bracket"] = { fg = p.comment },
        ["@punctuation.delimiter"] = { fg = p.comment },
        ["@punctuation.special"] = { fg = p.comment },
        ["@constant"] = { fg = p.constant },
        ["@constant.builtin"] = { fg = p.constant },
        ["@constant.macro"] = { fg = p.constant },
        ["@string"] = { fg = p.string },
        ["@string.regexp"] = { fg = p.string },
        ["@string.escape"] = { fg = p.tag, bold = true },
        ["@string.special"] = { fg = p.constant },
        ["@character"] = { fg = p.keyword },
        ["@character.special"] = { fg = p.keyword },
        ["@number"] = { fg = p.constant },
        ["@number.float"] = { fg = p.constant },
        ["@boolean"] = { fg = p.constant },
        ["@annotation"] = { fg = p.type },
        ["@attribute"] = { fg = p.type },
        ["@attribute.builtin"] = { fg = p.type },
        ["@module"] = { fg = p.constant },
        ["@function"] = { fg = p.func },
        ["@function.builtin"] = { fg = p.func },
        ["@function.macro"] = { fg = p.func },
        ["@function.method"] = { fg = p.func },
        ["@variable"] = { fg = p.variable },
        ["@variable.builtin"] = { fg = p.constant },
        ["@variable.parameter"] = { fg = p.variable_other },
        ["@variable.parameter.reference"] = { fg = p.variable_other },
        ["@variable.member"] = { fg = p.variable_other },
        ["@property"] = { fg = p.constant },
        ["@constructor"] = { fg = p.func },
        ["@label"] = { fg = p.constant },
        ["@keyword"] = { fg = p.keyword },
        ["@keyword.conditional"] = { fg = p.keyword },
        ["@keyword.repeat"] = { fg = p.keyword },
        ["@keyword.return"] = { fg = p.keyword },
        ["@keyword.exception"] = { fg = p.keyword },
        ["@keyword.import"] = { fg = p.fg_soft },
        ["@operator"] = { fg = p.fg },
        ["@type"] = { fg = p.type },
        ["@type.builtin"] = { fg = p.type },
        ["@type.qualifier"] = { fg = p.keyword },
        ["@structure"] = { fg = p.type },
        ["@tag"] = { fg = p.tag },
        ["@tag.builtin"] = { fg = p.tag },
        ["@tag.delimiter"] = { fg = p.comment },
        ["@tag.attribute"] = { fg = p.variable_other },
        ["@markup.strong"] = { fg = p.fg_soft, bold = true },
        ["@markup.italic"] = { fg = p.fg_soft, italic = true },
        ["@markup.underline"] = { underline = true },
        ["@markup.strikethrough"] = { strikethrough = true },
        ["@markup.heading"] = { fg = p.constant, bold = true },
        ["@markup.raw"] = { fg = p.constant },
        ["@markup.raw.markdown"] = { fg = p.constant },
        ["@markup.raw.markdown_inline"] = { fg = p.constant },
        ["@markup.link.label"] = { fg = p.string, underline = false },
        ["@markup.link.url"] = { fg = p.accent_link, underline = true },
        ["@markup.quote"] = { fg = p.tag },
        ["@markup.list.checked"] = { fg = p.variable, bold = true },
        ["@markup.list.unchecked"] = { fg = p.variable, bold = true },
        ["@textReference"] = { fg = p.string },
        ["@diff.plus"] = { fg = p.diff_inserted, bg = p.diff_add },
        ["@diff.minus"] = { fg = p.diff_deleted, bg = p.diff_delete },
        ["@diff.delta"] = { fg = p.diff_changed, bg = p.diff_change },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.decorator"] = { link = "@attribute" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@type" },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.macro"] = { link = "@function.macro" },
        ["@lsp.type.member"] = { link = "@property" },
        ["@lsp.type.method"] = { link = "@function.method" },
        ["@lsp.type.namespace"] = { link = "@module" },
        ["@lsp.type.parameter"] = { link = "@variable.parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type" },
        ["@lsp.type.variable"] = { link = "@variable" },
        ["@lsp.typemod.keyword.controlFlow"] = { fg = p.keyword },
        ["@lsp.typemod.property.readonly"] = { link = "@constant" },
        ["@lsp.typemod.variable.constant"] = { link = "@constant" },
        ["@lsp.typemod.variable.readonly"] = { link = "@constant" },
    },
}
