return {
    'lewis6991/impatient.nvim',
    enabled = true,
    condition = function() if (vim.g.vscode) then return false end end,
    lazy = false,
    -- opts = {},
    -- version = {},
    -- dependencies = {},
    -- keys = {},
    -- cmd = {},
    -- events = {},
    -- ft = {},
    -- init = {},
    -- deactivate = {},
}
